### ISSUE TITLE
“Try it yourself”/“Do it at home” experiments 

### ISSUE THREAD

**Issue by eneary** [OSTP/PhysicsArtofModelling#13]
- One per chapter? or as needed?

**Comment by ryanmartinneutrino** [comment]
I'm thinking even a "Thinking about the material section" - where there could be little experiments to perform at home, as well as prompts to go anf research something on their own. Instead of having all of the usual "info boxes", I was thinking students could go and look up ways in which the material applies to the real world, in addition to the experiments to try at home.
