### ISSUE TITLE
Figures in examples - suggest format

### ISSUE THREAD

**Issue by ryanmartinneutrino** [OSTP/PhysicsArtofModelling#51]
Initially, I had put all the figures that go with the question from an example into the "body" (solution) of the environment. It seems that with the new Example environment, this can introduce a large whitespace. 
We thus need to move all of the figures that go with the question for an example into the question (which makes more sense anyway). Because of the \\ in the example environment, I think the figure has to be the first thing in the example. I think the structure has to be:
\begin{example}{\label{ex:myexample} \capfig{}{figure.png}{caption}
  This is the question text.}
  Here is the solution
\end{example}

Ideally, we could put the figure after the text for the question, but I suspect that this would break the examples that don't have a figure.

**Comment by owoodman** [comment]
I modified the example environment in the final version that I merged on Friday. I think you should now be able to put the figure after the text in the question.
I think that the white space issue is because the titles of the boxes are raised. It only seems to be an issue for the Example boxes because they're the largest. I'm going to modify the formatting so that the titles aren't raised for those boxes.

**Comment by ryanmartinneutrino** [comment]
Ok, we can play around with it a little - the raised titles do look good!

**Comment by owoodman** [comment]
Ok. I want to keep the raised titles if possible so hopefully I can find a way to make it work
